# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json /app
COPY package-lock.json /app
RUN npm install --silent

# add app
COPY . /app

# open port
EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]